services:
  - docker

#before_install:

script:
  - docker build -t hardworking-gopher/docker-practice .

#after_success:
#  - docker build -t hardworking-gopher/docker-practice .

language: go
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "visits"
  env: "visits-env"
  bucket: "elasticbeanstalk-eu-north-1-182399714917"
  bucket_path: "visits"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: feature/travis-ci-deployment

