dist: jammy
language: go

services:
  - docker

#before_install:

script:
  - docker build -t hardworking-gopher/docker-practice .

#after_success:
#  - docker build -t hardworking-gopher/docker-practice .

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "visits"
  env: "visits-env"
  bucket: "elasticbeanstalk-us-east-1-841162702957"
  bucket_path: "visits"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: feature/travis-ci-deployment

