dist: jammy
language: go

jobs:
  include:
    - stage: build
      if: type = pull_request
      script:
        - echo "Building and testing PR..."
        - go build ./cmd
        - go test ./...

    - stage: deploy
      if: branch = master AND type = push  # Deploy only on merge to master
      script:
        - echo "Deploying to AWS Elastic Beanstalk..."
      deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "visits"
        env: "visits-env"
        bucket_name: "elasticbeanstalk-us-east-1-841162702957"
        bucket_path: "visits"
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
