dist: jammy
language: go

services:
  - docker

before_install:
  - docker build -t hardworking-gopher/docker-practice .


#script:
# TODO: Perform testing before moving forward with deployment

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "visits"
  env: "visits-env"
  bucket: "elasticbeanstalk-us-east-1-841162702957"
  bucket_path: "visits"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    # TODO: Perform tests and builds on PRs
    # TODO: Perform deploy on merge to master
    branch: feature/travis-ci-deployment
