sudo: required

services:
  - docker

#before_install:

script:
  - docker build -t hardworking-gopher/docker-practice .

#after_success:

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: "visits"
  env: "visits-env"
  bucket_name: "elasticbeanstalk-eu-north-1-182399714917"
  bucket_path: "visits"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
#  on:
#    branch: master
