dist: jammy
language: go

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

jobs:
  include:
    - stage: build
      if: type = pull_request
      script:
        - echo "Building and testing PR..."
        - docker build -t pandaemoniumplaza/docker-practice:latest -t pandaemoniumplaza/docker-practice:$SHA .
        - echo "Pushing image to Docker hub..."
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push pandaemoniumplaza/docker-practice:latest
        - docker push pandaemoniumplaza/docker-practice:$SHA

    - stage: deploy
      if: branch = master AND type = push
      script:
        - echo "Deploying to AWS Elastic Beanstalk..."
      deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "visits"
        env: "visits-env"
        bucket_name: "elasticbeanstalk-us-east-1-841162702957"
        bucket_path: "visits"
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
