version: '3'
services:
    redis:
      image: 'redis'
      restart: 'on-failure'
    app:
      build: .
      # in case we need to use .dev dockerfile
      #build:
      # context: .
      # dockerfile: Dockerfile.dev
      restart: 'on-failure'
      ports:
        - '8080:8080'
      environment:
        REDIS_HOST_NAME: redis