version: '3'
services:
    redis:
      image: 'redis'
      restart: 'on-failure'
    app:
      build: .
      restart: 'on-failure'
      ports:
        - '8080:8080'
      environment:
        REDIS_HOST_NAME: redis